version: '3.5'

networks:
  backend:
    driver: 'bridge'

volumes:
  mysql:
    driver: 'local'

services:
  php-fpm:
    build:
      context: docker/php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - backend

  nginx:
    image: nginx:alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - php-fpm

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: default
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/.data/mysql:/var/lib/mysql
    networks:
      - backend
